### ISSUE TITLE
What is this counting down to?

### ISSUE THREAD

**Issue by tbeckenhauer** [munvoseli/xkcd-countdown#2]

**Comment by bens9775** [comment]
I also have this issue

**Comment by LazaroFilm** [comment]
"counting down to January 31, 15:00 UTC"

**Comment by cmacmillan** [comment]
It looks like some sort of plane to me

**Comment by AzureArmageddon** [comment]
At the moment seems like an animation of a plane entering the frame from the left

**Comment by Toby222** [comment]
The new What If? book
