### ISSUE TITLE
Including metadata?

### ISSUE THREAD

**Issue by GuillaumeFromage** [munvoseli/xkcd-countdown#4]
Hi, 

I don't know if that's where you want to go with this project, but in terms of helping with speculation on the nature of the reveal, it has been mentioned that the names of the images are actually the SHA256 hash of the image. So I thought that the first couple of images would have the same hash, so I downloaded them, to realize that they don't have any watermarking. So the image contained is the same. It appears however that the metadata weren't cleaned on the files, and that the differences are in those items.

Say, image 6a73d565838a58e4d3069ad6cc49cc1a1466a8e602c95fd752126900d2074e28.png has a History Instance ID of xmp.iid:d098626e-8e83-415d-a727-d12c6b9ccc74, xmp.iid:2aef6e8e-40c8-4425-af01-47eb2f566959 while image 98b1c93977c76fd31529ff07f8f6f83209ba69ccc5a6b245e3a1061d36093370.png has History Instance ID : xmp.iid:deb52396-329e-4e86-97a2-07c055daaab8, xmp.iid:5c9443ea-0c31-45a5-bbf4-183366f08b03 . 

Would it be in the scope of this project to include metadata with the images so people can mess around can see the difference? I can write the code, I just don't want to write a pull request if its not your intent.

My initial thoughts where that images only move a few pixel each frame, so it would possible to reduce the field of potential hash to test for, but those IDs add a lot of random bits to the images, but maybe these aren't truly random and therefore potentially deducible.

**Comment by munvoseli** [comment]
I do not want to pursue guessing future hashes as a part of this project, and I would not want to display the metadata for that purpose.

Displaying the metadata would be interesting to me for the purpose of displaying the metadata, but unless cross-origin resource sharing weren't an issue, I can't do that with JavaScript dynamically, and it would be a very large bag of worms that I am not ready look at quite yet, as it would require restructuring my thoughts and my code.

It is a fun idea, and I may try to display the metadata, but only after I have made some changes on my end.  I am not currently interested in PRs.  Thank you for offering tho

**Comment by GuillaumeFromage** [comment]
Lol, okay, I'll try patience then :D.
